#!/bin/bash

# Copy this script to a directory in your path

# Required on osx since it uses virtualbox
socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\" &
SOCAT_PID=$!

# Get the IP address for vboxnet0
IFCFG=$(ifconfig vboxnet0)
ADDR_REGEX="^.*inet[[:space:]]+(([[:digit:]]+)(\.[[:digit:]]+){3,3}).*$"
if [[ $IFCFG =~ $ADDR_REGEX ]]; then
  ADDR="${BASH_REMATCH[1]}"
else
  echo "Unable to find vboxnet0"
  exit 1
fi

CONTAINER_ID=$(docker run -d --net=host --name vscode \
                          -e DISPLAY="${ADDR}:0" \
                          -v $HOME:/home/user \
                          f5gary/vscode)
echo "${CONTAINER_ID}"
docker wait "${CONTAINER_ID}"
docker rm "${CONTAINER_ID}" >/dev/null
kill "${SOCAT_PID}"

